colorful:
	rm -f $(CURDIR)/icons/theme
	ln -s $(CURDIR)/icons/colorful $(CURDIR)/icons/theme
	pyrcc4 cs140adagide.qrc -o cs140adagide_qrc.py

symbolic:
	rm -f $(CURDIR)/icons/theme
	ln -s $(CURDIR)/icons/symbolic $(CURDIR)/icons/theme
	pyrcc4 cs140adagide.qrc -o cs140adagide_qrc.py
